// <auto-generated />
namespace _2KOLKIT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sase));
        
        string IMigrationMetadata.Id
        {
            get { return "201906031041370_sase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
